export enum DomainErrorCode {
  // WorkLog errors
  WORKLOG_LOCKED = 'WORKLOG_LOCKED',
  WORKLOG_CONTENT_REQUIRED = 'WORKLOG_CONTENT_REQUIRED',
  WORKLOG_CONTENT_TOO_LONG = 'WORKLOG_CONTENT_TOO_LONG',
  WORKLOG_FUTURE_DATE = 'WORKLOG_FUTURE_DATE',
  WORKLOG_LOOKBACK_EXCEEDED = 'WORKLOG_LOOKBACK_EXCEEDED',
  WORKLOG_ALREADY_DELETED = 'WORKLOG_ALREADY_DELETED',
  WORKLOG_ID_EMPTY = 'WORKLOG_ID_EMPTY',
  WORKLOG_ID_TOO_LONG = 'WORKLOG_ID_TOO_LONG',
  WORKLOG_PROJECT_ID_REQUIRED = 'WORKLOG_PROJECT_ID_REQUIRED',
  WORKLOG_PROJECT_ID_TOO_LONG = 'WORKLOG_PROJECT_ID_TOO_LONG',
  WORKLOG_EMPLOYEE_ID_REQUIRED = 'WORKLOG_EMPLOYEE_ID_REQUIRED',
  WORKLOG_EMPLOYEE_ID_TOO_LONG = 'WORKLOG_EMPLOYEE_ID_TOO_LONG',
  WORKLOG_UNLOCK_IDENTITY_REQUIRED = 'WORKLOG_UNLOCK_IDENTITY_REQUIRED',
  WORKLOG_UNLOCK_REASON_REQUIRED = 'WORKLOG_UNLOCK_REASON_REQUIRED',

  // Project errors
  PROJECT_ID_EMPTY = 'PROJECT_ID_EMPTY',
  PROJECT_ID_TOO_LONG = 'PROJECT_ID_TOO_LONG',
  PROJECT_ALREADY_DELETED = 'PROJECT_ALREADY_DELETED',
  PROJECT_NAME_REQUIRED = 'PROJECT_NAME_REQUIRED',
  PROJECT_NAME_TOO_LONG = 'PROJECT_NAME_TOO_LONG',
  PROJECT_DESCRIPTION_TOO_LONG = 'PROJECT_DESCRIPTION_TOO_LONG',
  PROJECT_INVALID_STATUS = 'PROJECT_INVALID_STATUS',
  PROJECT_COMPLETE_ONLY_ACTIVE = 'PROJECT_COMPLETE_ONLY_ACTIVE',
  PROJECT_ARCHIVE_INVALID_STATUS = 'PROJECT_ARCHIVE_INVALID_STATUS',
}
